services:
  django-db:
    image: postgres
    restart: unless-stopped
    container_name: django-db
    volumes:
      - ${DJANGO_POSTGRES_DATA}:/var/lib/postgresql/data/
    env_file:
      - .env
  naturblick-django:
    build: .
    command: gunicorn --config gunicorn_config.py
    container_name: naturblick-django
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - django-db
