# Generated by Django 5.1.2 on 2024-11-20 14:52

import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nature', models.CharField(choices=[('Fauna', 'Fauna'), ('Flora', 'Flora')], max_length=5)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesid', models.CharField(max_length=255, unique=True)),
                ('sciname', models.CharField(max_length=255)),
                ('wikipedia', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_er', models.CharField(blank=True, max_length=255, null=True)),
                ('nbclassid', models.CharField(blank=True, max_length=255, null=True)),
                ('red_list_germany', models.CharField(blank=True, choices=[('gefahrdet', 'gefährdet'), ('Vorwarnliste', 'Vorwarnliste'), ('ausgestorben oder verschollen', 'ausgestorben oder verschollen'), ('vomAussterbenBedroht', 'vom Aussterben bedroht'), ('starkGefahrdet', 'stark gefährdet'), ('GefahrdungUnbekanntenAusmasses', 'Gefährdung unbekannten Ausmasses'), ('extremSelten', 'extrem selten'), ('DatenUnzureichend', 'Daten unzureichend'), ('ungefahrdet', 'ungefährdet'), ('nichtBewertet', 'nicht bewertet'), ('keinNachweis', 'kein Nachweis')], max_length=255, null=True)),
                ('iucncategory', models.CharField(blank=True, choices=[('NE', 'NE'), ('DD', 'DD'), ('LC', 'LC'), ('NT', 'NT'), ('VU', 'VU'), ('EN', 'EN'), ('CR', 'CR'), ('EW', 'EW'), ('EX', 'EX')], max_length=2, null=True)),
                ('activity_start_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('activity_end_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('activity_start_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('activity_end_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('gbifusagekey', models.IntegerField(blank=True, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_created_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='species.group')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='species_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'species',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='species.species')),
                ('human_interaction', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('er', 'Easy Read')], max_length=2)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_names', to='species.species')),
            ],
            options={
                'db_table': 'species_name',
            },
        ),
        migrations.CreateModel(
            name='Faunaportrait',
            fields=[
                ('portrait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='species.portrait')),
                ('male_description', models.TextField(blank=True, null=True)),
                ('female_description', models.TextField(blank=True, null=True)),
                ('juvenile_description', models.TextField(blank=True, null=True)),
                ('tracks', models.TextField(blank=True, null=True)),
                ('audioTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('audioLicense', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fauna_portrait',
            },
            bases=('species.portrait',),
        ),
        migrations.CreateModel(
            name='Floraportrait',
            fields=[
                ('portrait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='species.portrait')),
                ('leaf_description', models.TextField(default='')),
                ('stem_axis_description', models.TextField(default='')),
                ('flower_description', models.TextField(default='')),
                ('fruit_description', models.TextField(default='')),
            ],
            options={
                'db_table': 'flora_portrait',
            },
            bases=('species.portrait',),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
        migrations.CreateModel(
            name='GoodToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(default='')),
                ('type', models.CharField(choices=[('use', 'usage'), ('mnc', 'mnemonic'), ('cuy', 'culturalhistory'), ('art', 'art'), ('muc', 'music'), ('lie', 'literature'), ('ore', 'originofname'), ('orn', 'origin'), ('toe', 'toxicityorusage'), ('otr', 'other')], max_length=3)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
    ]
