# Generated by Django 5.1.2 on 2024-11-27 08:25

import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avatars')),
                ('image_owner', models.CharField(max_length=255)),
                ('image_ownerLink', models.URLField(blank=True, null=True)),
                ('image_source', models.URLField()),
                ('image_license', models.CharField(max_length=64)),
                ('cropping', image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('er', 'Easy Read')], max_length=2)),
                ('human_interaction', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nature', models.CharField(choices=[('Fauna', 'Fauna'), ('Flora', 'Flora')], max_length=5)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portrait_images')),
                ('image_owner', models.CharField(max_length=255)),
                ('image_ownerLink', models.URLField(blank=True, null=True)),
                ('image_source', models.URLField()),
                ('image_license', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faunaportrait',
            fields=[
                ('portrait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='species.portrait')),
                ('male_description', models.TextField(blank=True, null=True)),
                ('female_description', models.TextField(blank=True, null=True)),
                ('juvenile_description', models.TextField(blank=True, null=True)),
                ('tracks', models.TextField(blank=True, null=True)),
                ('audioTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('audioLicense', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fauna_portrait',
            },
            bases=('species.portrait',),
        ),
        migrations.CreateModel(
            name='Floraportrait',
            fields=[
                ('portrait_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='species.portrait')),
                ('leaf_description', models.TextField(default='')),
                ('stem_axis_description', models.TextField(default='')),
                ('flower_description', models.TextField(default='')),
                ('fruit_description', models.TextField(default='')),
            ],
            options={
                'db_table': 'flora_portrait',
            },
            bases=('species.portrait',),
        ),
        migrations.CreateModel(
            name='AdditionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
        migrations.CreateModel(
            name='GoodToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(default='')),
                ('type', models.CharField(choices=[('usage', 'usage'), ('mnemonic', 'mnemonic'), ('culturalhistory', 'culturalhistory'), ('art', 'art'), ('music', 'music'), ('literature', 'literature'), ('originofname', 'originofname'), ('origin', 'origin'), ('toxicityorusage', 'toxicityorusage'), ('other', 'other')], max_length=15)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_orientation', models.CharField(choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], max_length=10)),
                ('display_ratio', models.CharField(choices=[('4-3', '4-3'), ('3-4', '3-4')], max_length=3)),
                ('grid_ratio', models.CharField(choices=[('1-2', '1-2'), ('5-7', '5-7'), ('1-1', '1-1'), ('7-5', '7-5'), ('2-1', '2-1')], max_length=3)),
                ('focus_point_vertical', models.FloatField()),
                ('focus_point_horizontal', models.FloatField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='species.image')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesid', models.CharField(max_length=255, unique=True)),
                ('wikipedia', models.URLField(blank=True, max_length=255, null=True)),
                ('nbclassid', models.CharField(blank=True, max_length=255, null=True)),
                ('red_list_germany', models.CharField(blank=True, choices=[('gefahrdet', 'gefährdet'), ('Vorwarnliste', 'Vorwarnliste'), ('ausgestorben oder verschollen', 'ausgestorben oder verschollen'), ('vomAussterbenBedroht', 'vom Aussterben bedroht'), ('starkGefahrdet', 'stark gefährdet'), ('GefahrdungUnbekanntenAusmasses', 'Gefährdung unbekannten Ausmasses'), ('extremSelten', 'extrem selten'), ('DatenUnzureichend', 'Daten unzureichend'), ('ungefahrdet', 'ungefährdet'), ('nichtBewertet', 'nicht bewertet'), ('keinNachweis', 'kein Nachweis')], max_length=255, null=True)),
                ('iucncategory', models.CharField(blank=True, choices=[('NE', 'NE'), ('DD', 'DD'), ('LC', 'LC'), ('NT', 'NT'), ('VU', 'VU'), ('EN', 'EN'), ('CR', 'CR'), ('EW', 'EW'), ('EX', 'EX')], max_length=2, null=True)),
                ('activity_start_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('activity_end_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=9, null=True)),
                ('activity_start_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('activity_end_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('gbifusagekey', models.IntegerField(blank=True, null=True)),
                ('accepted', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='avatar', to='species.avatar')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_created_by', to=settings.AUTH_USER_MODEL)),
                ('female_avatar', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='female_avatar', to='species.avatar')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='species', to='species.group')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='species_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'species',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='SimilarSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differences', models.TextField()),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='species.species')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='species.portraitimageinfo')),
                ('fun_fact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fun_fact', to='species.portraitimageinfo')),
                ('in_the_city', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_the_city', to='species.portraitimageinfo')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_image', to='species.species')),
            ],
        ),
        migrations.AddField(
            model_name='portrait',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='species.species'),
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('er', 'Easy Read'), ('sf', 'Scientific')], max_length=2)),
                ('isPrimary', models.BooleanField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_names', to='species.species')),
            ],
            options={
                'db_table': 'species_name',
            },
        ),
        migrations.CreateModel(
            name='UnambigousFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.portrait')),
            ],
        ),
    ]
