# Generated by Django 5.1.2 on 2025-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='plantnetpowoid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='engdescription',
            field=models.TextField(blank=True, null=True, verbose_name='English description'),
        ),
        migrations.AlterField(
            model_name='character',
            name='engname',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gerdescription',
            field=models.TextField(blank=True, null=True, verbose_name='German description'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gername',
            field=models.CharField(max_length=255, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='charactervalue',
            name='engname',
            field=models.CharField(max_length=255, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='charactervalue',
            name='gername',
            field=models.CharField(max_length=255, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='sourcesimprint',
            name='name',
            field=models.CharField(choices=[('sound_recogniotion_images', 'Lauterkennung Bilder'), ('sound_recogniotion_sounds', 'Lauterkennung Tonaufnahmen'), ('ident_keys', 'Bestimmungsschlüssel')], max_length=32, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='sourcesimprint',
            name='scie_name',
            field=models.CharField(max_length=255, verbose_name='German description'),
        ),
        migrations.AlterField(
            model_name='sourcesimprint',
            name='scie_name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English description'),
        ),
        migrations.AlterField(
            model_name='species',
            name='engname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gbifusagekey',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='GBIF usagekey'),
        ),
        migrations.AlterField(
            model_name='species',
            name='gername',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='German name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='sciname',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Scientific name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Wikipedia link'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='German name'),
        ),
    ]
