# Generated by Django 5.1.2 on 2025-04-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantnetPowoidMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantnetpowoid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('species_plantnetpowoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species', to_field='plantnetpowoid')),
            ],
            options={
                'db_table': 'plantnet_powoid_mapping',
            },
        ),
    ]
