# Generated by Django 5.1.2 on 2025-04-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_remove_charactervalue_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='avatar',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, to='species.avatar'),
        ),
    ]
