# Generated by Django 5.1.2 on 2025-06-12 08:35

import django.db.models.deletion
import species.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_alter_species_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faunaportraitaudiofile',
            name='audio_spectrogram',
        ),
        migrations.AlterField(
            model_name='faunaportraitaudiofile',
            name='audio_file',
            field=models.FileField(upload_to='audio_files', validators=[species.validators.validate_mp3]),
        ),
        migrations.AlterField(
            model_name='species',
            name='avatar',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_species', to='species.avatar'),
        ),
        migrations.AlterField(
            model_name='species',
            name='female_avatar',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='female_avatar_species', to='species.avatar'),
        ),
    ]
