# Generated by Django 5.1.2 on 2025-06-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_alter_faunaportraitaudiofile_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faunaportraitaudiofile',
            name='audio_spectrogram',
        ),
    ]
