# Generated by Django 5.1.2 on 2025-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_remove_faunaportraitaudiofile_audio_spectrogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='ecosystem_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
