# Generated by Django 5.1.2 on 2025-07-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_portrait_ecosystem_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtoknow',
            name='type',
            field=models.CharField(choices=[('usage', 'Usage'), ('mnemonic', 'Mnemonic'), ('culturalhistory', 'Culturalhistory'), ('art', 'Art'), ('music', 'Music'), ('literature', 'Literature'), ('originofname', 'Origin of name'), ('origin', 'Origin'), ('toxicityorusage', 'Toxicity or usage'), ('blossom', 'Blossom'), ('lifeform', 'Lifeform'), ('distribution', 'Distribution'), ('other', 'Other')], max_length=15),
        ),
    ]
