# Generated by Django 5.1.2 on 2025-07-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_portrait_ecosystem_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='group_images'),
        ),
        migrations.AddField(
            model_name='group',
            name='svg',
            field=models.FileField(max_length=255, null=True, upload_to='group_svg'),
        ),
    ]
