# Generated by Django 5.1.2 on 2025-08-19 12:17

import species.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_group_image_group_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='engname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='gername',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='has_characters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='has_portraits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_fieldbookfilter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='group_images', validators=[species.validators.validate_group_image, species.validators.validate_png]),
        ),
        migrations.AlterField(
            model_name='group',
            name='nature',
            field=models.CharField(blank=True, choices=[('fauna', 'Fauna'), ('flora', 'Flora')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='svg',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='group_svg', validators=[species.validators.validate_svg]),
        ),
    ]
