# Generated by Django 5.1.2 on 2025-10-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_group_engname_group_gername_group_has_characters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionallink',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='goodtoknow',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='similarspecies',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='unambigousfeature',
            options={'ordering': ['ordering']},
        ),
        migrations.RenameField(
            model_name='additionallink',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='goodtoknow',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='similarspecies',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='unambigousfeature',
            old_name='order',
            new_name='ordering',
        ),
        migrations.CreateModel(
            name='LeichtPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodtoknow_image', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='goodtoknow_image', to='species.portraitimagefile')),
                ('recognize_image', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='recognize_image', to='species.portraitimagefile')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='species.species')),
            ],
        ),
        migrations.CreateModel(
            name='LeichtGoodToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ordering', models.IntegerField()),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.leichtportrait')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeichtRecognize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ordering', models.IntegerField()),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.leichtportrait')),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
    ]
