# Generated by Django 5.1.2 on 2025-10-01 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_alter_additionallink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leichtportrait',
            name='goodtoknow_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goodtoknow_image', to='species.portraitimagefile'),
        ),
        migrations.AlterField(
            model_name='leichtportrait',
            name='recognize_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recognize_image', to='species.portraitimagefile'),
        ),
    ]
