# Generated by Django 5.1.2 on 2025-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_alter_leichtportrait_goodtoknow_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leichtportrait',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
