# Generated by Django 5.1.2 on 2025-10-17 07:12

import django.db.models.deletion
import species.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_leichtportrait_level'),
    ]

    operations = [
        migrations.RunSQL(
            sql='TRUNCATE TABLE species_leichtportrait RESTART IDENTITY CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('owner_link', models.URLField(blank=True, max_length=255, null=True)),
                ('source', models.URLField(max_length=1024)),
                ('license', models.CharField(max_length=64)),
                ('audio_file', models.FileField(upload_to='leicht_audio_files', validators=[species.validators.validate_mp3])),
            ],
            options={
                'db_table': 'audio_file',
            },
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('owner_link', models.URLField(blank=True, max_length=255, null=True)),
                ('source', models.URLField(max_length=1024)),
                ('license', models.CharField(max_length=64)),
                ('image', models.ImageField(height_field='height', max_length=255, upload_to='images', width_field='width')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='species',
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='species.avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='name',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.audiofile'),
        ),
        migrations.AlterField(
            model_name='leichtportrait',
            name='goodtoknow_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goodtoknow_image', to='species.imagefile'),
        ),
        migrations.AlterField(
            model_name='leichtportrait',
            name='recognize_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recognize_image', to='species.imagefile'),
        ),
    ]
