# Generated by Django 5.1.2 on 2025-10-30 09:32

import django.db.models.deletion
import image_cropping.fields
import species.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_leichtportrait_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropping', image_cropping.fields.ImageRatioField('imagefile__image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
            options={
                'db_table': 'imagecrop',
            },
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='recognize_image',
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='species',
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='name',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterModelTable(
            name='leichtgoodtoknow',
            table='leichtgtk',
        ),
        migrations.AlterModelTable(
            name='leichtportrait',
            table='leichtportrait',
        ),
        migrations.AlterModelTable(
            name='leichtrecognize',
            table='leichtrecognize',
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('owner_link', models.URLField(blank=True, max_length=255, null=True)),
                ('source', models.URLField(max_length=1024)),
                ('license', models.CharField(max_length=64)),
                ('audio_file', models.FileField(upload_to='leicht_audio_files', validators=[species.validators.validate_mp3])),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.species')),
            ],
            options={
                'db_table': 'audiofile',
            },
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.audiofile'),
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='species.imagecrop'),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('owner_link', models.URLField(blank=True, max_length=255, null=True)),
                ('source', models.URLField(max_length=1024)),
                ('license', models.CharField(max_length=64)),
                ('image', models.ImageField(height_field='height', max_length=255, upload_to='images', width_field='width')),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.species')),
            ],
            options={
                'db_table': 'imagefile',
            },
        ),
        migrations.AddField(
            model_name='imagecrop',
            name='imagefile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
        migrations.AlterField(
            model_name='leichtportrait',
            name='goodtoknow_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='goodtoknow_image', to='species.imagefile'),
        ),
    ]
