# Generated by Django 5.1.2 on 2025-10-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_imagecrop_remove_leichtportrait_recognize_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='avatar_new',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_species_new', to='species.imagecrop'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='species',
            name='female_avatar_new',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='female_avatar_species_new', to='species.imagecrop'),
            preserve_default='True',
        ),
    ]
