# Generated by Django 5.1.2 on 2025-10-21 12:32

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0013_audiofile_imagefile_remove_leichtportrait_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCrop',
            fields=[
                ('imagefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='species.imagefile')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
            ],
            bases=('species.imagefile',),
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='recognize_image',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.species'),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='species.species'),
        ),
        migrations.AlterField(
            model_name='leichtportrait',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='species.imagecrop'),
        ),
    ]
