# Generated by Django 5.1.2 on 2025-10-31 12:52
import os

from django.db import migrations
from django.conf import settings

from species.models import ImageCrop, ImageFile, Species

def copy_avatar_data(apps, schema_editor):
    media_root = os.path.abspath(settings.MEDIA_ROOT)

    for species in Species.objects.all():
        avatar = species.avatar
        if avatar:
            try:
                old_path = f"{media_root}/{avatar.image.name}"
                image_file = ImageFile(species=species, owner=avatar.owner, owner_link=avatar.owner_link,
                                       source=avatar.source,
                                       license=avatar.license, image=avatar.image )
                image_file.image.name = f"images/{avatar.image.name.split('/')[-1]}"
                image_file.save()

                image_crop = ImageCrop(imagefile=image_file, cropping=avatar.cropping)
                image_crop.save()
                species.avatar_new = image_crop
                species.save(update_fields=['avatar_new'])

                os.rename(old_path, f"{media_root}/{image_file.image.name}")
            except FileNotFoundError:
                print(f"File avatar '{old_path}' NOT FOUND")

        female_avatar = species.female_avatar
        if female_avatar:
            try:
                female_old_path = f"{media_root}/{female_avatar.image.name}"
                female_image_file = ImageFile(species=species, owner=female_avatar.owner, owner_link=female_avatar.owner_link,
                                       source=female_avatar.source,
                                       license=female_avatar.license, image=female_avatar.image)
                female_image_file.image.name = f"images/{female_avatar.image.name.split('/')[-1]}"
                female_image_file.save()
                female_image_crop = ImageCrop(imagefile=female_image_file, cropping=female_avatar.cropping)
                female_image_crop.save()
                species.female_avatar_new = female_image_crop
                species.save(update_fields=['female_avatar_new'])
                os.rename(female_old_path, f"{media_root}/{female_image_file.image.name}")
            except FileNotFoundError:
                print(f"File female avatar '{old_path}' NOT FOUND")


class Migration(migrations.Migration):
    dependencies = [
        ('species', '0014_species_avatar_new_species_female_avatar_new'),
    ]

    operations = [
        migrations.RunPython(copy_avatar_data)
    ]
