# Generated by Django 5.1.2 on 2025-10-31 12:52

from django.db import migrations

from species.models import ImageCrop, ImageFile, Species


## avatar
# image = models.ImageField(upload_to="avatar_images", max_length=255)
# owner = models.CharField(max_length=255)
# owner_link = URLField(blank=True, null=True, max_length=255)
# source = URLField(max_length=1024)
# license = models.CharField(max_length=64)
# cropping = ImageRatioField('image', '400x400', size_warning=True)

## imagefile
# id = models.BigAutoField(primary_key=True)
# species = models.ForeignKey("Species", null=True, blank=True, on_delete=CASCADE)
# owner = models.CharField(max_length=255)
# owner_link = URLField(blank=True, null=True, max_length=255)
# source = URLField(max_length=1024)
# license = models.CharField(max_length=64)
# image = models.ImageField(upload_to="images", max_length=255, width_field='width', height_field='height')
# width = models.IntegerField(default=0)
# height = models.IntegerField(default=0)


from django.core.files.base import ContentFile

def copy_avatar_data(apps, schema_editor):

    for species in Species.objects.all():
        avatar = species.avatar
        if avatar:
            picture_copy = ContentFile(avatar.image.read())
            new_picture_name = avatar.image.name.split("/")[-1]
            image_file = ImageFile(species=species, owner=avatar.owner, owner_link=avatar.owner_link,
                                   source=avatar.source,
                                   license=avatar.license, image=ImageFile() )   #  avatar.image
            image_file.image.save(new_picture_name, picture_copy)
            image_file.save()

            image_crop = ImageCrop(imagefile=image_file, cropping=avatar.cropping).save()
            species.avatar_new = image_crop
            species.save(update_fields=['avatar_new'])

        female_avatar = species.female_avatar
        if female_avatar:
            image_file = ImageFile(species=species, owner=female_avatar.owner, owner_link=female_avatar.owner_link,
                                   source=female_avatar.source,
                                   license=female_avatar.license, image=female_avatar.image)
            image_file.save()
            female_image_crop = ImageCrop(imagefile=image_file, cropping=female_avatar.cropping).save()
            species.female_avatar = female_image_crop
            species.save(update_fields=['female_avatar_new'])


class Migration(migrations.Migration):
    dependencies = [
        ('species', '0014_species_avatar_new_species_female_avatar_new'),
    ]

    operations = [
        migrations.RunPython(copy_avatar_data)
    ]
