# Generated by Django 5.1.2 on 2025-11-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0015_copy_avatars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='species',
            name='female_avatar',
        ),
    ]
