# Generated by Django 5.1.2 on 2025-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0016_remove_species_avatar_remove_species_female_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='birdnetid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
