# Generated by Django 5.1.2 on 2025-11-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0017_species_birdnetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='descmeta',
            name='image_file',
            field=models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
        migrations.AddField(
            model_name='funfactmeta',
            name='image_file',
            field=models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
        migrations.AddField(
            model_name='inthecitymeta',
            name='image_file',
            field=models.ForeignKey(db_default=1, on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
    ]
