# Generated by Django 5.1.2 on 2025-11-11 13:34
import os
import shutil

from django.conf import settings
from django.db import migrations

def copy_portrait_imagefiles(apps, schema_editor):
    DescMeta = apps.get_model("species", "DescMeta")
    FunFactMeta = apps.get_model("species", "FunFactMeta")
    InTheCityMeta = apps.get_model("species", "InTheCityMeta")
    ImageFile = apps.get_model("species", "ImageFile")

    for m in DescMeta.objects.all():
        copy_meta(m, ImageFile)
    for m in FunFactMeta.objects.all():
        copy_meta(m, ImageFile)
    for m in InTheCityMeta.objects.all():
        copy_meta(m, ImageFile)


def copy_meta(m, ImageFile):
    media_root = os.path.abspath(settings.MEDIA_ROOT)
    pif = m.portrait_image_file
    old_path = f"{media_root}/{pif.image.name}"
    image_file = ImageFile(species=pif.species, owner=pif.owner, owner_link=pif.owner_link,
                           source=pif.source,
                           license=pif.license, image=pif.image)
    image_file.image.name = f"images/{pif.image.name.split('/')[-1]}"
    image_file.save()
    m.image_file = image_file
    m.save(update_fields=['image_file'])
    shutil.copyfile(old_path, f"{media_root}/{image_file.image.name}")


class Migration(migrations.Migration):
    dependencies = [
        ('species', '0018_descmeta_image_file_funfactmeta_image_file_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_portrait_imagefiles)
    ]
