# Generated by Django 5.1.2 on 2025-11-12 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0019_copy_portraitimagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='birdnetid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BirdnetIdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birdnetid', models.PositiveIntegerField(unique=True)),
                ('species_birdnetid', models.ForeignKey(limit_choices_to={'birdnetid__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='species.species', to_field='birdnetid')),
            ],
            options={
                'db_table': 'birdnet_id_mapping',
            },
        ),
    ]
