# Generated by Django 5.1.2 on 2025-11-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0020_alter_species_birdnetid_birdnetidmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species'),
        ),
    ]
