# Generated by Django 5.1.2 on 2025-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0021_alter_imagefile_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
