# Generated by Django 5.1.2 on 2025-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0022_species_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantnetpowoidmapping',
            name='plantnetpowoid',
            field=models.CharField(default='FIXME', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
