# Generated by Django 6.0.1 on 2026-02-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0023_alter_plantnetpowoidmapping_plantnetpowoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descmeta',
            name='portrait_image_file',
        ),
        migrations.RemoveField(
            model_name='funfactmeta',
            name='portrait_image_file',
        ),
        migrations.RemoveField(
            model_name='inthecitymeta',
            name='portrait_image_file',
        ),
        migrations.DeleteModel(
            name='PortraitImageFile',
        ),
    ]
