# Generated by Django 6.0.1 on 2026-02-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0024_remove_descmeta_portrait_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descmeta',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
        migrations.AlterField(
            model_name='funfactmeta',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
        migrations.AlterField(
            model_name='inthecitymeta',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.imagefile'),
        ),
    ]
