# Generated by Django 6.0.1 on 2026-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0025_alter_descmeta_image_file_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='similarspecies',
            constraint=models.UniqueConstraint(fields=('species', 'portrait'), name='unique_species_portrait'),
        ),
    ]
