# Generated by Django 6.0.1 on 2026-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0026_similarspecies_unique_species_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
