# Generated by Django 6.0.1 on 2026-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0027_species_rank_species_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='gbif_incompatible',
            field=models.BooleanField(default=False, verbose_name='Taxa is incompatible with the GBIF taxonomy'),
        ),
    ]
