# Generated by Django 6.0.1 on 2026-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0028_species_gbif_incompatible'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('institution', models.TextField()),
            ],
            options={
                'db_table': 'evaluation_author',
            },
        ),
    ]
