# Generated by Django 6.0.1 on 2026-03-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0028_species_gbif_incompatible'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_set', to='species.species'),
        ),
        migrations.AddField(
            model_name='species',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_set', to='species.species'),
        ),
    ]
