# Generated by Django 6.0.1 on 2026-04-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    def add_authors(apps, schema_editor):
        EvaluationAuthor = apps.get_model('species', 'EvaluationAuthor')

        EvaluationAuthor.objects.bulk_create([
            EvaluationAuthor(id=1, name="Susan Karlebowski", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=2, name="Team Forschungsfall Nachtigall",
                                institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=3, name="Ulrike Sturm", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=15, name="Carin Wenzlokat", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=16, name="Glaucia Santos", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=6, name="Praktikant=innen", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=7, name="Vrinda Schallnau", institution="Museum für Naturkunde Berlin"),
            EvaluationAuthor(id=11, name="Hauke Kuhlmann", institution="Museum für Naturkunde Berlin")
        ])

    dependencies = [
        ('species', '0029_evaluationauthor'),
    ]

    operations = [
        migrations.RunPython(add_authors)
    ]
