# Generated by Django 6.0.1 on 2026-04-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0030_auto_20260415_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faunaportrait',
            name='tracks',
        ),
    ]
