# Generated by Django 6.0.1 on 2026-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0031_remove_faunaportrait_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='avatar_not_found',
            field=models.BooleanField(default=False, verbose_name='Avatar was not found'),
        ),
    ]
