# Generated by Django 6.0.1 on 2026-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0032_species_avatar_not_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='primary_name_not_found',
            field=models.BooleanField(default=False, verbose_name='Primary name was not found'),
        ),
    ]
