# Generated by Django 6.0.1 on 2026-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0033_species_primary_name_not_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='gbif_needs_approval',
            field=models.BooleanField(default=False, verbose_name='Gbif needs approval'),
        ),
    ]
