# Generated by Django 6.0.1 on 2026-07-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0034_species_gbif_needs_approval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeichtGoodToKnow',
            new_name='LeichtDescription',
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='goodtoknow_image',
        ),
        migrations.RemoveField(
            model_name='leichtportrait',
            name='level',
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='initially_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leichtportrait',
            name='location',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterModelTable(
            name='leichtdescription',
            table='leichtdescription',
        ),
        migrations.DeleteModel(
            name='LeichtRecognize',
        ),
    ]
