# Generated by Django 6.0.1 on 2026-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0035_rename_leichtgoodtoknow_leichtdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='colid',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
