# Generated by Django 6.0.8 on 2026-09-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0036_species_colid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoLSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colid', models.CharField(max_length=5, unique=True)),
                ('sciname', models.CharField(max_length=255, verbose_name='Scientific name')),
                ('rank', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('accepted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_set', to='species.colspecies')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='species.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_set', to='species.colspecies')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='species.species')),
            ],
            options={
                'verbose_name': 'Catalogue of Life taxon',
                'db_table': 'col_species',
            },
        ),
    ]
