# Generated by Django 6.0.8 on 2026-09-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0037_colspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_set', to='species.species'),
        ),
        migrations.AlterField(
            model_name='colspecies',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='species.species'),
        ),
    ]
