# Generated by Django 6.0.8 on 2026-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0038_species_parent_alter_colspecies_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='sciname',
            field=models.CharField(max_length=255, verbose_name='Scientific name'),
        ),
    ]
