name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  packages: write  # Allow the workflow to push packages (docker images)

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/naturblick/django:$GITHUB_REF_NAME .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/naturblick/django:$GITHUB_REF_NAME