name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t ${{ vars.HALLOFTOOLS }}/naturblick/django:$GITHUB_REF_NAME .
      - run: docker push ${{ vars.HALLOFTOOLS }}/naturblick/django:$GITHUB_REF_NAME

